using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HomebrewDot.Net.Rimworld.State;

namespace HomebrewDot.Net.Rimworld.Filtering
{
    /// <summary>
    /// A filter that can be applied to a collection of items based on a scope. The filter is generated by a policy and is associated with a specific scope.
    /// </summary>
    /// <typeparam name="TScope">The type of the scope.</typeparam>
    /// <typeparam name="TItem">The type of the items to be filtered.</typeparam>
    public interface IDynamicFilter<TScope, in TItem>
    {
        /// <summary>
        /// The instance the filter is scoped to.
        /// </summary>
        TScope Scope { get; }
        /// <summary>
        /// The policy that generated this filter.
        /// </summary>
        IDynamicPolicy<TScope, TItem> Policy { get; }

        /// <summary>
        /// Determines whether the specified item passes the filter criteria given <see cref="Scope"/>.
        /// </summary>
        /// <param name="item">The item to be evaluated by the filter.</param>
        /// <returns><c>true</c> if the item passes the filter; otherwise, <c>false</c>.</returns>
        bool Filter(TItem item);
        /// <summary>
        /// Updates the filter's internal state based on changes to the scope or other relevant factors. This method should be called whenever there is a change in the scope or any other conditions that might affect the filter's behavior, allowing it to adjust its criteria accordingly.
        /// </summary>
        /// <param name="stateStore">A state store that provides access to the current state of the scope.</param>
        /// <returns>True if any state changes were detected and the filter was updated; otherwise, false.</returns>
        bool Update(IStateStore<TScope> stateStore);
    }
}
